### ISSUE TITLE
Sticky header covers scroll targets

### ISSUE THREAD

**Issue by mootari** [observablehq/feedback#401]
**Describe the bug**

When a notebook contains edits, Observable sticks the notebook menu bar to to the top of the viewport.

This bar covers jump targets (anchors, search results) and thus several impedes navigation and orientation within a notebook.

**Expected behavior**

Scrolling to elements is offset by the height of the sticky bar.

**Additional context**

This is an longstanding problem that has likely been touched on in other issues as well.

**Comment by mootari** [comment]
**Workaround**

Add a user style sheet with the following content:
```css
@-moz-document url-prefix("https://observablehq.com/") {
  #__next .node-focus .ͼ5 {
    background-color: var(--near-white);
  }
  #__next div[data-node-id], .cm-content > div {
    scroll-margin-top: 52px;
    scroll-margin-bottom: 52px;
  }
}
```
This also fixes the scrolling issues described in https://github.com/observablehq/feedback/issues/291#issuecomment-1079665613.

**Comment by CobusT** [comment]
@mootari Could you attach an example video of this problem. I can't seem to reproduce it (see video clip)

https://user-images.githubusercontent.com/10869236/163855361-a1e3f8f1-a7d0-4719-9521-68521710ce32.mov

.

**Comment by mbostock** [comment]
Cobus, we fixed this recently.

**Comment by mootari** [comment]
@CobusT It's fixed for search results, but still a problem for anchors:
1. Go to https://observablehq.com/@ambassadors/input-history@2582
2. In the first cell *output*, look for the line that says "Go to: inputHistory, statesWidget, Changelog, Todos"
3. Click either "inputHistory" or "statesWidget"

**Comment by mootari** [comment]
This is still an issue for anchors.

**Comment by mootari** [comment]
Sticky headers still cover the target:

<img width="869" alt="image" src="https://github.com/observablehq/feedback/assets/322014/529c3d39-a230-43c6-aae8-88321e67c9ae">
